package fr.robie.craftengineconverter.api.enums;

public enum ComponentFlag {
    MAX_STACK_SIZE("max_stack_size"),
    MAX_DAMAGE("max_damage"),
    DAMAGE("damage"),
    UNBREAKABLE("unbreakable"),
    CUSTOM_NAME("custom_name"),
    ITEM_NAME("item_name"),
    ITEM_MODEL("item_model"),
    LORE("lore"),
    RARITY("rarity"),
    ENCHANTMENTS("enchantments"),
    CAN_PLACE_ON("can_place_on"),
    CAN_BREAK("can_break"),
    ATTRIBUTE_MODIFIERS("attribute_modifiers"),
    CUSTOM_MODEL_DATA("custom_model_data"),
    TOOLTIP_DISPLAY("tooltip_display"),
    REPAIR_COST("repair_cost"),
    ENCHANTMENT_GLINT_OVERRIDE("enchantment_glint_override"),
    INTANGIBLE_PROJECTILE("intangible_projectile"),
    FOOD("food"),
    CONSUMABLE("consumable"),
    USE_REMAINDER("use_remainder"),
    USE_COOLDOWN("use_cooldown"),
    DAMAGE_RESISTANT("damage_resistant"),
    TOOL("tool"),
    WEAPON("weapon"),
    ENCHANTABLE("enchantable"),
    EQUIPPABLE("equippable"),
    REPAIRABLE("repairable"),
    GLIDER("glider"),
    TOOLTIP_STYLE("tooltip_style"),
    DEATH_PROTECTION("death_protection"),
    BLOCKS_ATTACKS("blocks_attacks"),
    STORED_ENCHANTMENTS("stored_enchantments"),
    DYED_COLOR("dyed_color"),
    MAP_COLOR("map_color"),
    MAP_ID("map_id"),
    MAP_DECORATIONS("map_decorations"),
    MAP_POST_PROCESSING("map_post_processing"),
    CHARGED_PROJECTILES("charged_projectiles"),
    BUNDLE_CONTENTS("bundle_contents"),
    POTION_CONTENTS("potion_contents"),
    POTION_DURATION_SCALE("potion_duration_scale"),
    SUSPICIOUS_STEW_EFFECTS("suspicious_stew_effects"),
    WRITABLE_BOOK_CONTENT("writable_book_content"),
    WRITTEN_BOOK_CONTENT("written_book_content"),
    TRIM("trim"),
    INSTRUMENT("instrument"),
    PROVIDES_TRIM_MATERIAL("provides_trim_material"),
    OMINOUS_BOTTLE_AMPLIFIER("ominous_bottle_amplifier"),
    JUKEBOX_PLAYABLE("jukebox_playable"),
    PROVIDES_BANNER_PATTERNS("provides_banner_patterns"),
    RECIPES("recipes"),
    LODESTONE_TRACKER("lodestone_tracker"),
    FIREWORK_EXPLOSION("firework_explosion"),
    FIREWORKS("fireworks"),
    PROFILE("profile"),
    NOTE_BLOCK_SOUND("note_block_sound"),
    BANNER_PATTERNS("banner_patterns"),
    BASE_COLOR("base_color"),
    POT_DECORATIONS("pot_decorations"),
    CONTAINER("container"),
    BLOCK_DATA("block_state"),
    CONTAINER_LOOT("container_loot"),
    BREAK_SOUND("break_sound"),
    VILLAGER_VARIANT("villager/variant"),
    WOLF_VARIANT("wolf/variant"),
    WOLF_SOUND_VARIANT("wolf/sound_variant"),
    WOLF_COLLAR("wolf/collar"),
    FOX_VARIANT("fox/variant"),
    SALMON_SIZE("salmon/size"),
    PARROT_VARIANT("parrot/variant"),
    TROPICAL_FISH_PATTERN("tropical_fish/pattern"),
    TROPICAL_FISH_BASE_COLOR("tropical_fish/base_color"),
    TROPICAL_FISH_PATTERN_COLOR("tropical_fish/pattern_color"),
    MOOSHROOM_VARIANT("mooshroom/variant"),
    RABBIT_VARIANT("rabbit/variant"),
    PIG_VARIANT("pig/variant"),
    COW_VARIANT("cow/variant"),
    CHICKEN_VARIANT("chicken/variant"),
    FROG_VARIANT("frog/variant"),
    HORSE_VARIANT("horse/variant"),
    PAINTING_VARIANT("painting/variant"),
    LLAMA_VARIANT("llama/variant"),
    AXOLOTL_VARIANT("axolotl/variant"),
    CAT_VARIANT("cat/variant"),
    CAT_COLLAR("cat/collar"),
    SHEEP_COLOR("sheep/color"),
    SHULKER_COLOR("shulker/color");

    private final String key;

    ComponentFlag(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
